# Generated by Django 4.2 on 2023-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
