# Generated by Django 4.2 on 2023-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_description_listing_sold_listing_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("R", "Rap"),
                    ("C", "Cloud"),
                    ("E", "Electro"),
                ],
                max_length=5,
            ),
        ),
    ]
