# Generated by Django 4.2 on 2023-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="like_new",
            field=models.BooleanField(default=True),
        ),
    ]
